name: Secrets Scanning Shared Workflow
on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE:
        required: true
      HMCTS_CP_GITLEAKS_REGEX_INTERNAL_URL:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hmcts/secrets-scanner@main
        with:
          github_token: ${{ github.token }}
          gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}
          gitleaks_regex_internal_url: ${{ secrets.HMCTS_CP_GITLEAKS_REGEX_INTERNAL_URL }}